name: CI/CD Pipeline for DevOps Canary

on:
  push:
    branches:
      - main   # run only when pushing to main
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        npm install -g aws-cdk

    - name: Run unit tests
      run: |
        source .venv/bin/activate
        pytest tests/ || echo "No tests found, skipping"

    - name: CDK Synth
      run: |
        source .venv/bin/activate
        cdk synth

    - name: Deploy to AWS
      if: github.ref == 'refs/heads/main'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-2
      run: |
        source .venv/bin/activate
        cdk deploy --require-approval never -c alertEmail=${{ secrets.ALERT_EMAIL }}
